### ISSUE TITLE
Driver build failure 

### ISSUE THREAD

**Issue by adonnini** [authenteq/java-bigchaindb-driver#55] opened 2017-12-06 03:20 UTC
Hi,
I tried to build the driver using the ./gradlew build command from the command line as indicated in the documentation.
The build failed with the output listed below.
What am I doing wrong?
Thanks,
Alex Donnini

:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:6: error: package javax.websocket does not exist
import javax.websocket.ClientEndpoint;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:7: error: package javax.websocket does not exist
import javax.websocket.CloseReason;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:8: error: package javax.websocket does not exist
import javax.websocket.ContainerProvider;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:9: error: package javax.websocket does not exist
import javax.websocket.OnClose;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:10: error: package javax.websocket does not exist
import javax.websocket.OnMessage;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:11: error: package javax.websocket does not exist
import javax.websocket.OnOpen;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:12: error: package javax.websocket does not exist
import javax.websocket.Session;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:13: error: package javax.websocket does not exist
import javax.websocket.WebSocketContainer;
                      ^
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:20: error: cannot find symbol
@ClientEndpoint
 ^
  symbol: class ClientEndpoint
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:26: error: cannot find symbol
        Session userSession = null;
        ^
  symbol:   class Session
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:57: error: cannot find symbol
        public void onOpen(Session userSession) {
                           ^
  symbol:   class Session
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:71: error: cannot find symbol
        public void onClose(Session userSession, CloseReason reason) {
                            ^
  symbol:   class Session
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:71: error: cannot find symbol
        public void onClose(Session userSession, CloseReason reason) {
                                                 ^
  symbol:   class CloseReason
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:56: error: cannot find symbol
        @OnOpen
         ^
  symbol:   class OnOpen
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:70: error: cannot find symbol
        @OnClose
         ^
  symbol:   class OnClose
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:83: error: cannot find symbol
        @OnMessage
         ^
  symbol:   class OnMessage
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:40: error: cannot find symbol
                        WebSocketContainer container = ContainerProvider.getWebSocketContainer();
                        ^
  symbol:   class WebSocketContainer
  location: class BigchainDbWSSessionManager
/home/adonnini1/Development/BigchainDB/java-bigchaindb-driver/src/main/java/com/authenteq/ws/BigchainDbWSSessionManager.java:40: error: cannot find symbol
                        WebSocketContainer container = ContainerProvider.getWebSocketContainer();
                                                       ^
  symbol:   variable ContainerProvider
  location: class BigchainDbWSSessionManager
18 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.788 secs

**Comment by alvin-reyes** [comment] 2017-12-06 09:46
@bodia , @tzclucian  can you check and see if there is an issue?

**Comment by tzclucian** [comment] 2017-12-06 09:47
I'll double check in a minute.

**Comment by tzclucian** [comment] 2017-12-06 09:50
I can reproduce it.

```sh
mvn clean install
```
Works just fine.

```sh
./gradlew build
```
Fails with the same output as the reported posted.

PS: I'm not very familiar with gradle.

**Comment by adonnini** [comment] 2017-12-14 02:55
Hi,

Do you have an update on this issue? 

At present, as it says in the notes to the changes "Got rid of maven, now using gradle only". Maven does not work on the version available for download. I tried and the build failed:

"[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java-bigchaindb-driver 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 15.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 KB at 215.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 KB at 357.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 KB at 229.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 KB at 364.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom (8 KB at 139.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom (9 KB at 119.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom (30 KB at 433.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom (15 KB at 245.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar (29 KB at 443.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.6.2/maven-compiler-plugin-3.6.2.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.6.2/maven-compiler-plugin-3.6.2.pom (11 KB at 179.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/30/maven-plugins-30.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/30/maven-plugins-30.pom (10 KB at 174.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/30/maven-parent-30.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/30/maven-parent-30.pom (41 KB at 602.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom (16 KB at 259.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.6.2/maven-compiler-plugin-3.6.2.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.6.2/maven-compiler-plugin-3.6.2.jar (74 KB at 954.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom (11 KB at 173.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom (14 KB at 232.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar (30 KB at 472.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom (6 KB at 101.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.jar (34 KB at 535.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 KB at 231.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom (13 KB at 221.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/15/maven-parent-15.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/15/maven-parent-15.pom (24 KB at 378.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/6/apache-6.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/6/apache-6.pom (13 KB at 227.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (204 KB at 1387.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom (7 KB at 102.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar (27 KB at 404.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.9.0/okhttp-3.9.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.9.0/okhttp-3.9.0.pom (2 KB at 25.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/squareup/okhttp3/parent/3.9.0/parent-3.9.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/squareup/okhttp3/parent/3.9.0/parent-3.9.0.pom (17 KB at 289.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Downloaded: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom (5 KB at 81.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.13.0/okio-1.13.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.13.0/okio-1.13.0.pom (2 KB at 27.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/squareup/okio/okio-parent/1.13.0/okio-parent-1.13.0.pom
Downloaded: http://repo.maven.apache.org/maven2/com/squareup/okio/okio-parent/1.13.0/okio-parent-1.13.0.pom (5 KB at 81.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/net/i2p/crypto/eddsa/0.2.0/eddsa-0.2.0.pom
Downloaded: http://repo.maven.apache.org/maven2/net/i2p/crypto/eddsa/0.2.0/eddsa-0.2.0.pom (7 KB at 97.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
Downloaded: http://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom (12 KB at 198.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom (57 KB at 742.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/apache/15/apache-15.pom (15 KB at 256.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/json/json/20170516/json-20170516.pom
Downloaded: http://repo.maven.apache.org/maven2/org/json/json/20170516/json-20170516.pom (6 KB at 93.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Downloaded: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom (7 KB at 112.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom
Downloaded: http://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.pom (2 KB at 31.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/google/code/gson/gson-parent/2.8.2/gson-parent-2.8.2.pom
Downloaded: http://repo.maven.apache.org/maven2/com/google/code/gson/gson-parent/2.8.2/gson-parent-2.8.2.pom (4 KB at 63.0 KB/sec)
[WARNING] The POM for org.interledger:java-crypto-conditions:jar:2.0.0-SNAPSHOT is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.pom
Downloaded: http://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.pom (2 KB at 19.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom
Downloaded: http://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.pom (24 KB at 355.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom (766 B at 14.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom (2 KB at 26.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/bundles/tyrus-standalone-client/1.9/tyrus-standalone-client-1.9.pom
Downloaded: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/bundles/tyrus-standalone-client/1.9/tyrus-standalone-client-1.9.pom (7 KB at 106.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/bundles/tyrus-bundles/1.9/tyrus-bundles-1.9.pom
Downloaded: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/bundles/tyrus-bundles/1.9/tyrus-bundles-1.9.pom (4 KB at 53.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/tyrus-project/1.9/tyrus-project-1.9.pom
Downloaded: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/tyrus-project/1.9/tyrus-project-1.9.pom (28 KB at 447.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/net/java/jvnet-parent/5/jvnet-parent-5.pom
Downloaded: http://repo.maven.apache.org/maven2/net/java/jvnet-parent/5/jvnet-parent-5.pom (9 KB at 149.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.9.0/okhttp-3.9.0.jar
Downloading: http://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar
Downloading: http://repo.maven.apache.org/maven2/net/i2p/crypto/eddsa/0.2.0/eddsa-0.2.0.jar
Downloading: http://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
Downloading: http://repo.maven.apache.org/maven2/org/json/json/20170516/json-20170516.jar
Downloaded: http://repo.maven.apache.org/maven2/com/squareup/okhttp3/okhttp/3.9.0/okhttp-3.9.0.jar (397 KB at 1792.9 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar
Downloaded: http://repo.maven.apache.org/maven2/org/json/json/20170516/json-20170516.jar (56 KB at 227.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar
Downloaded: http://repo.maven.apache.org/maven2/net/i2p/crypto/eddsa/0.2.0/eddsa-0.2.0.jar (61 KB at 155.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.jar
Downloaded: http://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar (228 KB at 1322.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Downloaded: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar (44 KB at 354.6 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/bundles/tyrus-standalone-client/1.9/tyrus-standalone-client-1.9.jar
Downloaded: http://repo.maven.apache.org/maven2/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar (80 KB at 148.8 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.jar (308 KB at 1398.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar (278 KB at 321.6 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/glassfish/tyrus/bundles/tyrus-standalone-client/1.9/tyrus-standalone-client-1.9.jar (1981 KB at 1870.1 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar (3201 KB at 1318.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.458 s
[INFO] Finished at: 2017-12-13T21:48:10-05:00
[INFO] Final Memory: 9M/479M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project java-bigchaindb-driver: Could not resolve dependencies for project com.authenteq:java-bigchaindb-driver:jar:0.0.1-SNAPSHOT: Could not find artifact org.interledger:java-crypto-conditions:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
"

Thanks,

Alex Donnini

**Comment by nemccarthy** [comment] 2017-12-15 04:22
I get the same issue with MVN - this looks like this artifact doesnt exist in mvn central org.interledger:java-crypto-conditions:jar:2.0.0-SNAPSHOT

**Comment by adonnini** [comment] 2017-12-18 23:12
Are these relevant?

https://github.com/hyperledger/quilt/issues/14

https://github.com/interledger/java-crypto-conditions

**Comment by manolodewiner** [comment] 2017-12-21 13:12
In the Pom is written this:

> You must install java-crypto-conditions-2.0.0-SNAPSHOT.jar in your local Maven repository with the following

	`mvn install:install-file -Dfile=<absolute_path_to_repo>\libs\java-crypto-conditions-2.0.0-SNAPSHOT.jar -DgroupId=org.interledger -DartifactId=java-crypto-conditions -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar`
		

**Another possible solution** is to change this in the Pom:
```
                <dependency>
			<groupId>org.interledger</groupId>
			<artifactId>java-crypto-conditions</artifactId>
			<version>2.0.0-SNAPSHOT</version>
			<!-- <systemPath>${project.basedir}/libs/java-crypto-conditions-2.0.0-SNAPSHOT.jar</systemPath> -->
		</dependency>
```

for this:
```
                <dependency>
		    <groupId>org.interledger</groupId>
		    <artifactId>java-crypto-conditions</artifactId>
		    <version>2.0.0-SNAPSHOT</version>
		    <scope>system</scope>
		    <systemPath>${project.basedir}/libs/java-crypto-conditions-2.0.0-SNAPSHOT.jar</systemPath>
		</dependency>
```

**Comment by alvin-reyes** [comment] 2018-02-20 01:54
This is already fixed by https://github.com/authenteq/java-bigchaindb-driver/pull/58

**Closed by alvin-reyes** 2018-02-20 01:54 UTC
Labels: bug, build fix
